# Generated by Django 2.2.4 on 2019-08-13 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20190809_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votecategory',
            options={'verbose_name_plural': 'Vote Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'category')},
        ),
        migrations.CreateModel(
            name='VoteCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.Candidate')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.VoteCategory')),
            ],
            options={
                'unique_together': {('candidate', 'category')},
            },
        ),
    ]
